### ISSUE TITLE
react-native-payments: TypeScript type annotation 'TSObjectKeyword' is unsupported in NativeModule specs.

### ISSUE THREAD

**Issue by ArtemLakhurov** [rnw-community/rnw-community#238]
Hi, I have an error when trying to instal pods: 
UnsupportedTypeAnnotationParserError: Module NativePayments: TypeScript type annotation 'TSObjectKeyword' is unsupported in NativeModule specs.

package.json:

"react-native": "0.75.4",
"@rnw-community/react-native-payments": "^0.75.4"

Also err reproduced on your example project. 
New arch is turned off

I will be very grateful for your feedback 🙏

**Comment by denysoleksiienko** [comment]
same with `"@rnw-community/react-native-payments": "^0.75.4"`, but not with v. `"0.75.3"`

**Comment by ArtemLakhurov** [comment]
> same with `"@rnw-community/react-native-payments": "^0.75.4"`, but not with v. `"0.75.3"`

Thank you! I rolled back to 0.75.3 and the pods installed fine.

**Comment by vitalyiegorov** [comment]
@ArtemLakhurov Can you please check the [example](https://github.com/rnw-community/rnw-community/tree/master/packages/react-native-payments-example) if it works for you?

**Comment by denysoleksiienko** [comment]
This bug present in versions > 0.75.3. On android can't build Gradle and on ios can't install Pods (old arch or new arch)

```
Task :rnw-community_react-native-payments:generateCodegenSchemaFromJavaScript FAILED
/Users/mac/app/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:650
        throw parsingErrors[0];
        ^

UnsupportedTypeAnnotationParserError: Module NativePayments: TypeScript type annotation 'TSObjectKeyword' is unsupported in NativeModule specs.
    at translateTypeAnnotation (/Users/mac/app/node_modules/@react-native/codegen/lib/parsers/typescript/modules/index.js:392:15)
    at /Users/mac/app/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:424:11
    at guard (/Users/mac/app/node_modules/@react-native/codegen/lib/parsers/utils.js:31:14)
    at translateFunctionTypeAnnotation (/Users/mac/app/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:418:25)
    at buildPropertySchema (/Users/mac/app/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:535:7)
    at /Users/mac/app/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:856:22
    at guard (/Users/mac/app/node_modules/@react-native/codegen/lib/parsers/utils.js:31:14)
    at /Users/mac/app/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:836:14
    at Array.map (<anonymous>)
    at buildModuleSchema (/Users/mac/app/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:818:6) {
  nodes: [
    Node {
      type: 'TSObjectKeyword',
      start: 579,
      end: 585,
      loc: SourceLocation {
        start: Position { line: 14, column: 40, index: 579 },
        end: Position { line: 14, column: 46, index: 585 },
        filename: undefined,
        identifierName: undefined
      }
    }
  ],
  typeAnnotationType: 'TSObjectKeyword'
}

Node.js v20.18.0
```

**Comment by vitalyiegorov** [comment]
fixed in https://github.com/rnw-community/rnw-community/releases/tag/v0.77.0 please check

**Comment by denysoleksiienko** [comment]
@vitalyiegorov Yes, it works in `0.77.0`
